TAX_OFFICE_OPTIONS = [
    { "value": "5202", "label": "Aachen-Kreis" },
    { "value": "5201", "label": "Aachen-Stadt" },
    { "value": "2850", "label": "Aalen" },
    { "value": "5301", "label": "Ahaus" },
    { "value": "2601", "label": "Alsfeld-Lauterbach Verwaltungsstelle Alsfeld" },
    { "value": "2629", "label": "Alsfeld-Lauterbach Verwaltungsstelle Lauterbach" },
    { "value": "5302", "label": "Altena" },
    { "value": "4166", "label": "Altenburg" },
    { "value": "2702", "label": "Altenkirchen-Hachenburg" },
    { "value": "9201", "label": "Amberg" },
    { "value": "3062", "label": "Angermünde" },
    { "value": "3217", "label": "Annaberg-B. - Annaberg" },
    { "value": "9203", "label": "Ansbach mit Außenstellen" },
    { "value": "5303", "label": "Arnsberg" },
    { "value": "9204", "label": "Aschaffenburg" },
    { "value": "2353", "label": "Aschendorf - Papenburg" },
    { "value": "9102", "label": "Augsburg-Land" },
    { "value": "9103", "label": "Augsburg-Stadt" },
    { "value": "9101", "label": "Augsburg-Stadt Arbeitnehmerbereich" },
    { "value": "2354", "label": "Aurich-Wittmund" },
    { "value": "2851", "label": "Backnang" },
    { "value": "2355", "label": "Bad Bentheim" },
    { "value": "2603", "label": "Bad Homburg v. d. Höhe - Bad Homburg vor der Höhe" },
    { "value": "9205", "label": "Bad Kissingen" },
    { "value": "2706", "label": "Bad Kreuznach" },
    { "value": "2701", "label": "Bad Neuenahr-Ahrweiler" },
    { "value": "9206", "label": "Bad Neustadt a.d.S." },
    { "value": "2130", "label": "Bad Oldesloe - Stormarn" },
    { "value": "2111", "label": "Bad Segeberg" },
    { "value": "2889", "label": "Bad Urach" },
    { "value": "2833", "label": "Baden-Baden" },
    { "value": "2836", "label": "Baden-Baden Außenstelle Bühl" },
    { "value": "2853", "label": "Balingen" },
    { "value": "9207", "label": "Bamberg" },
    { "value": "3204", "label": "Bautzen" },
    { "value": "9208", "label": "Bayreuth" },
    { "value": "5304", "label": "Beckum" },
    { "value": "2605", "label": "Bensheim" },
    { "value": "2617", "label": "Bensheim Außenstelle Fürth" },
    { "value": "9105", "label": "Berchtesgaden-Laufen" },
    { "value": "5203", "label": "Bergheim" },
    { "value": "5204", "label": "Bergisch Gladbach" },
    { "value": "1113", "label": "Berlin - Charlottenburg" },
    { "value": "1114", "label": "Berlin - Friedrichshain-Kreuzberg" },
    { "value": "1132", "label": "Berlin - Lichtenberg" },
    { "value": "1133", "label": "Berlin - Marzahn-Hellersdorf" },
    { "value": "1134", "label": "Berlin - Mitte/Tiergarten" },
    { "value": "1116", "label": "Berlin - Neukölln" },
    { "value": "1135", "label": "Berlin - Pankow/Weißensee" },
    { "value": "1131", "label": "Berlin - Prenzlauer Berg" },
    { "value": "1117", "label": "Berlin - Reinickendorf" },
    { "value": "1118", "label": "Berlin - Schöneberg" },
    { "value": "1119", "label": "Berlin - Spandau" },
    { "value": "1120", "label": "Berlin - Steglitz" },
    { "value": "1121", "label": "Berlin - Tempelhof" },
    { "value": "1136", "label": "Berlin - Treptow-Köpenick" },
    { "value": "1123", "label": "Berlin - Wedding" },
    { "value": "1124", "label": "Berlin - Wilmersdorf" },
    { "value": "1125", "label": "Berlin - Zehlendorf" },
    { "value": "1127", "label": "Berlin - für Körperschaften I" },
    { "value": "1137", "label": "Berlin - für Körperschaften II" },
    { "value": "1129", "label": "Berlin - für Körperschaften III" },
    { "value": "1130", "label": "Berlin - für Körperschaften IV" },
    { "value": "2854", "label": "Biberach" },
    { "value": "2879", "label": "Biberach Außenstelle Riedlingen" },
    { "value": "5349", "label": "Bielefeld-Außenstadt" },
    { "value": "5305", "label": "Bielefeld-Innenstadt" },
    { "value": "2855", "label": "Bietigheim-Bissingen" },
    { "value": "2708", "label": "Bingen-Alzey" },
    { "value": "2710", "label": "Bitburg-Prüm" },
    { "value": "3116", "label": "Bitterfeld-Wolfen" },
    { "value": "5306", "label": "Bochum-Mitte" },
    { "value": "5350", "label": "Bochum-Süd" },
    { "value": "5206", "label": "Bonn-Außenstadt" },
    { "value": "5205", "label": "Bonn-Innenstadt" },
    { "value": "5307", "label": "Borken" },
    { "value": "5308", "label": "Bottrop" },
    { "value": "3048", "label": "Brandenburg an der Havel - Brandenburg" },
    { "value": "2313", "label": "Braunschweig-Helmstedt" },
    { "value": "2314", "label": "Braunschweig-Wilhelmstr." },
    { "value": "2460", "label": "Bremen" },
    { "value": "2475", "label": "Bremerhaven" },
    { "value": "2349", "label": "Bremerhaven - Wesermünde" },
    { "value": "5309", "label": "Brilon" },
    { "value": "2830", "label": "Bruchsal" },
    { "value": "5224", "label": "Brühl" },
    { "value": "2315", "label": "Buchholz in der Nordheide" },
    { "value": "2316", "label": "Burgdorf" },
    { "value": "9106", "label": "Burghausen" },
    { "value": "2856", "label": "Böblingen" },
    { "value": "5310", "label": "Bünde" },
    { "value": "3057", "label": "Calau" },
    { "value": "2845", "label": "Calw" },
    { "value": "2317", "label": "Celle" },
    { "value": "9211", "label": "Cham mit Außenstelle Bad Kötzting" },
    { "value": "3215", "label": "Chemnitz-Mitte" },
    { "value": "3214", "label": "Chemnitz-Süd" },
    { "value": "2356", "label": "Cloppenburg" },
    { "value": "9212", "label": "Coburg" },
    { "value": "5312", "label": "Coesfeld" },
    { "value": "3056", "label": "Cottbus" },
    { "value": "2318", "label": "Cuxhaven" },
    { "value": "9107", "label": "Dachau" },
    { "value": "2607", "label": "Darmstadt" },
    { "value": "9108", "label": "Deggendorf" },
    { "value": "2357", "label": "Delmenhorst" },
    { "value": "3114", "label": "Dessau-Roßlau" },
    { "value": "5313", "label": "Detmold" },
    { "value": "2608", "label": "Dieburg" },
    { "value": "2609", "label": "Dillenburg" },
    { "value": "9109", "label": "Dillingen" },
    { "value": "9110", "label": "Dingolfing" },
    { "value": "5101", "label": "Dinslaken" },
    { "value": "5315", "label": "Dortmund-Hörde" },
    { "value": "5317", "label": "Dortmund-Ost" },
    { "value": "5316", "label": "Dortmund-Unna" },
    { "value": "5314", "label": "Dortmund-West" },
    { "value": "3202", "label": "Dresden-Nord" },
    { "value": "3203", "label": "Dresden-Süd" },
    { "value": "5107", "label": "Duisburg-Hamborn" },
    { "value": "5109", "label": "Duisburg-Süd" },
    { "value": "5134", "label": "Duisburg-West" },
    { "value": "3236", "label": "Döbeln" },
    { "value": "5207", "label": "Düren" },
    { "value": "5103", "label": "Düsseldorf-Altstadt" },
    { "value": "5147", "label": "Düsseldorf-Mettmann" },
    { "value": "5133", "label": "Düsseldorf-Mitte" },
    { "value": "5105", "label": "Düsseldorf-Nord" },
    { "value": "5106", "label": "Düsseldorf-Süd" },
    { "value": "9112", "label": "Ebersberg" },
    { "value": "3065", "label": "Eberswalde" },
    { "value": "2129", "label": "Eckernförde-Schleswig" },
    { "value": "9113", "label": "Eggenfelden" },
    { "value": "2858", "label": "Ehingen" },
    { "value": "9171", "label": "Eichstätt" },
    { "value": "3237", "label": "Eilenburg" },
    { "value": "4155", "label": "Eisenach" },
    { "value": "3118", "label": "Eisleben" },
    { "value": "2113", "label": "Elmshorn" },
    { "value": "2358", "label": "Emden-Norden" },
    { "value": "2805", "label": "Emmendingen" },
    { "value": "9114", "label": "Erding" },
    { "value": "4151", "label": "Erfurt" },
    { "value": "5208", "label": "Erkelenz" },
    { "value": "9216", "label": "Erlangen" },
    { "value": "2610", "label": "Eschwege-Witzenhausen Verwaltungsstelle Eschwege" },
    { "value": "2641", "label": "Eschwege-Witzenhausen Verwaltungsstelle Witzenhausen" },
    { "value": "5111", "label": "Essen-NordOst" },
    { "value": "5112", "label": "Essen-Süd" },
    { "value": "2859", "label": "Esslingen" },
    { "value": "2831", "label": "Ettlingen" },
    { "value": "5209", "label": "Euskirchen" },
    { "value": "2115", "label": "Flensburg" },
    { "value": "9217", "label": "Forchheim" },
    { "value": "3061", "label": "Frankfurt (Oder)" },
    { "value": "2613", "label": "Frankfurt am Main I" },
    { "value": "2612", "label": "Frankfurt am Main II" },
    { "value": "2645", "label": "Frankfurt am Main III" },
    { "value": "2614", "label": "Frankfurt am Main IV" },
    { "value": "2647", "label": "Frankfurt am Main V-Höchst Verwaltungsstelle Frankfurt" },
    { "value": "2615", "label": "Frankfurt am Main V-Höchst Verwaltungsstelle Höchst" },
    { "value": "3220", "label": "Freiberg" },
    { "value": "2807", "label": "Freiburg-Land" },
    { "value": "2813", "label": "Freiburg-Land Außenstelle Titisee-Neustadt" },
    { "value": "2806", "label": "Freiburg-Stadt" },
    { "value": "9115", "label": "Freising" },
    { "value": "2842", "label": "Freudenstadt" },
    { "value": "2616", "label": "Friedberg (Hessen)" },
    { "value": "2861", "label": "Friedrichshafen" },
    { "value": "2618", "label": "Fulda" },
    { "value": "9117", "label": "Fürstenfeldbruck" },
    { "value": "9218", "label": "Fürth" },
    { "value": "9119", "label": "Garmisch-Partenkirchen" },
    { "value": "5210", "label": "Geilenkirchen" },
    { "value": "5113", "label": "Geldern" },
    { "value": "2619", "label": "Gelnhausen" },
    { "value": "5319", "label": "Gelsenkirchen" },
    { "value": "3103", "label": "Genthin" },
    { "value": "4161", "label": "Gera" },
    { "value": "2620", "label": "Gießen" },
    { "value": "2319", "label": "Gifhorn" },
    { "value": "2321", "label": "Goslar-Bad Gandersheim" },
    { "value": "4156", "label": "Gotha" },
    { "value": "9157", "label": "Grafenau" },
    { "value": "4084", "label": "Greifswald" },
    { "value": "5114", "label": "Grevenbroich" },
    { "value": "3238", "label": "Grimma" },
    { "value": "2621", "label": "Groß-Gerau" },
    { "value": "5212", "label": "Gummersbach" },
    { "value": "9220", "label": "Gunzenhausen" },
    { "value": "2863", "label": "Göppingen" },
    { "value": "2862", "label": "Göppingen Außenstelle Geislingen" },
    { "value": "3207", "label": "Görlitz" },
    { "value": "2320", "label": "Göttingen" },
    { "value": "9121", "label": "Günzburg" },
    { "value": "4086", "label": "Güstrow" },
    { "value": "5351", "label": "Gütersloh" },
    { "value": "5321", "label": "Hagen" },
    { "value": "4087", "label": "Hagenow" },
    { "value": "3105", "label": "Haldensleben" },
    { "value": "3110", "label": "Halle (Saale)" },
    { "value": "2227", "label": "Hamburg für Großunternehmen in Hamburg" },
    { "value": "2241", "label": "Hamburg-Altona" },
    { "value": "2242", "label": "Hamburg-Am Tierpark" },
    { "value": "2243", "label": "Hamburg-Barmbek-Uhlenhorst" },
    { "value": "2245", "label": "Hamburg-Eimsbüttel" },
    { "value": "2246", "label": "Hamburg-Hansa" },
    { "value": "2247", "label": "Hamburg-Harburg" },
    { "value": "2248", "label": "Hamburg-Mitte" },
    { "value": "2249", "label": "Hamburg-Nord" },
    { "value": "2250", "label": "Hamburg-Oberalster" },
    { "value": "2244", "label": "Hamburg-Ost" },
    { "value": "2322", "label": "Hameln" },
    { "value": "5322", "label": "Hamm" },
    { "value": "2622", "label": "Hanau" },
    { "value": "2323", "label": "Hannover-Land I" },
    { "value": "2342", "label": "Hannover-Land I Außenstelle Springe" },
    { "value": "2327", "label": "Hannover-Land II" },
    { "value": "2324", "label": "Hannover-Mitte" },
    { "value": "2325", "label": "Hannover-Nord" },
    { "value": "2326", "label": "Hannover-Süd" },
    { "value": "5323", "label": "Hattingen" },
    { "value": "2116", "label": "Heide - Dithmarschen" },
    { "value": "2832", "label": "Heidelberg" },
    { "value": "2864", "label": "Heidenheim" },
    { "value": "2865", "label": "Heilbronn" },
    { "value": "2328", "label": "Helmstedt" },
    { "value": "5324", "label": "Herford" },
    { "value": "5325", "label": "Herne" },
    { "value": "9221", "label": "Hersbruck" },
    { "value": "2602", "label": "Hersfeld-Rotenburg Verwaltungsstelle Bad Hersfeld" },
    { "value": "2636", "label": "Hersfeld-Rotenburg Verwaltungsstelle Rotenburg" },
    { "value": "5135", "label": "Hilden" },
    { "value": "2330", "label": "Hildesheim-Alfeld" },
    { "value": "9222", "label": "Hilpoltstein" },
    { "value": "9223", "label": "Hof mit Außenstellen" },
    { "value": "2646", "label": "Hofheim am Taunus" },
    { "value": "2331", "label": "Holzminden" },
    { "value": "1075", "label": "Homburg" },
    { "value": "1085", "label": "Homburg - Außenst. St. Ingbert" },
    { "value": "3213", "label": "Hoyerswerda" },
    { "value": "5326", "label": "Höxter" },
    { "value": "5327", "label": "Ibbenbüren" },
    { "value": "2709", "label": "Idar-Oberstein" },
    { "value": "4154", "label": "Ilmenau" },
    { "value": "9124", "label": "Ingolstadt" },
    { "value": "5328", "label": "Iserlohn" },
    { "value": "2118", "label": "Itzehoe" },
    { "value": "4162", "label": "Jena" },
    { "value": "5213", "label": "Jülich" },
    { "value": "2719", "label": "Kaiserslautern" },
    { "value": "5119", "label": "Kamp-Lintfort" },
    { "value": "2834", "label": "Karlsruhe-Durlach" },
    { "value": "2835", "label": "Karlsruhe-Stadt" },
    { "value": "2625", "label": "Kassel I" },
    { "value": "2623", "label": "Kassel II-Hofgeismar Verwaltungsstelle Hofgeismar" },
    { "value": "2626", "label": "Kassel II-Hofgeismar Verwaltungsstelle Kassel" },
    { "value": "9125", "label": "Kaufbeuren m. ASt Füssen" },
    { "value": "9126", "label": "Kelheim" },
    { "value": "5115", "label": "Kempen" },
    { "value": "9127", "label": "Kempten-Immenstadt" },
    { "value": "2120", "label": "Kiel" },
    { "value": "9227", "label": "Kitzingen" },
    { "value": "5116", "label": "Kleve" },
    { "value": "2722", "label": "Koblenz" },
    { "value": "2809", "label": "Konstanz" },
    { "value": "2611", "label": "Korbach-Frankenberg Verwaltungsstelle Frankenberg" },
    { "value": "2627", "label": "Korbach-Frankenberg Verwaltungsstelle Korbach" },
    { "value": "5117", "label": "Krefeld" },
    { "value": "9228", "label": "Kronach" },
    { "value": "9229", "label": "Kulmbach" },
    { "value": "2723", "label": "Kusel-Landstuhl" },
    { "value": "2734", "label": "Kusel-Landstuhl für Erb/Schenk.St. Saarland" },
    { "value": "3052", "label": "Kyritz" },
    { "value": "5214", "label": "Köln-Altstadt" },
    { "value": "5215", "label": "Köln-Mitte" },
    { "value": "5217", "label": "Köln-Nord" },
    { "value": "5218", "label": "Köln-Ost" },
    { "value": "5216", "label": "Köln-Porz" },
    { "value": "5219", "label": "Köln-Süd" },
    { "value": "5223", "label": "Köln-West" },
    { "value": "3049", "label": "Königs Wusterhausen" },
    { "value": "2810", "label": "Lahr" },
    { "value": "2724", "label": "Landau" },
    { "value": "9131", "label": "Landsberg am Lech" },
    { "value": "9132", "label": "Landshut" },
    { "value": "2628", "label": "Langen" },
    { "value": "2117", "label": "Leck - Nordfriesland" },
    { "value": "2360", "label": "Leer (Ostfriesland)" },
    { "value": "3232", "label": "Leipzig I" },
    { "value": "3231", "label": "Leipzig II" },
    { "value": "5329", "label": "Lemgo" },
    { "value": "2870", "label": "Leonberg" },
    { "value": "5230", "label": "Leverkusen" },
    { "value": "9230", "label": "Lichtenfels" },
    { "value": "2630", "label": "Limburg-Weilburg Verwaltungsstelle Limburg" },
    { "value": "2638", "label": "Limburg-Weilburg Verwaltungsstelle Weilburg" },
    { "value": "9134", "label": "Lindau" },
    { "value": "2361", "label": "Lingen (Ems)" },
    { "value": "5330", "label": "Lippstadt" },
    { "value": "9231", "label": "Lohr a. Main mit Außenstellen" },
    { "value": "9232", "label": "Lohr a. Main mit Außenstellen - Grunderwerbsteuer" },
    { "value": "3050", "label": "Luckenwalde" },
    { "value": "2871", "label": "Ludwigsburg" },
    { "value": "2727", "label": "Ludwigshafen" },
    { "value": "3208", "label": "Löbau" },
    { "value": "2811", "label": "Lörrach" },
    { "value": "5331", "label": "Lübbecke" },
    { "value": "2122", "label": "Lübeck" },
    { "value": "5332", "label": "Lüdenscheid" },
    { "value": "5333", "label": "Lüdinghausen" },
    { "value": "2333", "label": "Lüneburg" },
    { "value": "3102", "label": "Magdeburg" },
    { "value": "2726", "label": "Mainz" },
    { "value": "2837", "label": "Mannheim-Neckarstadt" },
    { "value": "2838", "label": "Mannheim-Stadt" },
    { "value": "2606", "label": "Marburg-Biedenkopf Verwaltungsstelle Biedenkopf" },
    { "value": "2631", "label": "Marburg-Biedenkopf Verwaltungsstelle Marburg" },
    { "value": "5359", "label": "Marl" },
    { "value": "2729", "label": "Mayen" },
    { "value": "3209", "label": "Meißen" },
    { "value": "9138", "label": "Memmingen-Mindelheim" },
    { "value": "3112", "label": "Merseburg" },
    { "value": "1020", "label": "Merzig" },
    { "value": "5334", "label": "Meschede" },
    { "value": "2633", "label": "Michelstadt" },
    { "value": "9139", "label": "Miesbach" },
    { "value": "5335", "label": "Minden" },
    { "value": "3222", "label": "Mittweida" },
    { "value": "2730", "label": "Montabaur-Diez" },
    { "value": "2840", "label": "Mosbach" },
    { "value": "2846", "label": "Mosbach Außenstelle Walldürn" },
    { "value": "5121", "label": "Mönchengladbach" },
    { "value": "2848", "label": "Mühlacker" },
    { "value": "9141", "label": "Mühldorf" },
    { "value": "4157", "label": "Mühlhausen" },
    { "value": "5120", "label": "Mülheim an der Ruhr" },
    { "value": "2812", "label": "Müllheim" },
    { "value": "9147", "label": "München Gewinneinkünfte" },
    { "value": "9143", "label": "München Körperschaften/PersonenGesellschaften" },
    { "value": "9184", "label": "München Überschusseinkünfte" },
    { "value": "9182", "label": "München Überschusseinkünfte u. Beschränkt Steuerpfl." },
    { "value": "5336", "label": "Münster-Außenstadt" },
    { "value": "5337", "label": "Münster-Innenstadt" },
    { "value": "3051", "label": "Nauen" },
    { "value": "3119", "label": "Naumburg" },
    { "value": "9151", "label": "Neu-Ulm" },
    { "value": "4072", "label": "Neubrandenburg" },
    { "value": "4070", "label": "Neubrandenburg - RIA (Rentenempfänger im Ausland)" },
    { "value": "9235", "label": "Neumarkt i.d.Opf." },
    { "value": "2124", "label": "Neumünster" },
    { "value": "1030", "label": "Neunkirchen" },
    { "value": "5122", "label": "Neuss" },
    { "value": "2731", "label": "Neustadt" },
    { "value": "2732", "label": "Neuwied" },
    { "value": "2634", "label": "Nidda" },
    { "value": "2334", "label": "Nienburg/Weser" },
    { "value": "2363", "label": "Nordenham" },
    { "value": "2335", "label": "Northeim-Herzberg am Harz" },
    { "value": "9152", "label": "Nördlingen mit ASt Donauwörth" },
    { "value": "9238", "label": "Nürnberg-Nord" },
    { "value": "9240", "label": "Nürnberg-Süd" },
    { "value": "9241", "label": "Nürnberg-Zentral" },
    { "value": "2874", "label": "Nürtingen" },
    { "value": "2869", "label": "Nürtingen Außenstelle Kirchheim" },
    { "value": "5123", "label": "Oberhausen-Nord" },
    { "value": "5124", "label": "Oberhausen-Süd" },
    { "value": "9202", "label": "Obernburg am Main mit Außenstelle Amorbach" },
    { "value": "2635", "label": "Offenbach am Main I" },
    { "value": "2644", "label": "Offenbach am Main II" },
    { "value": "2814", "label": "Offenburg" },
    { "value": "2801", "label": "Offenburg Außenstelle Achern" },
    { "value": "2808", "label": "Offenburg Außenstelle Kehl" },
    { "value": "2823", "label": "Offenburg Außenstelle Wolfach" },
    { "value": "2364", "label": "Oldenburg (Oldenburg)" },
    { "value": "2125", "label": "Oldenburg - Ostholstein" },
    { "value": "5338", "label": "Olpe" },
    { "value": "3053", "label": "Oranienburg" },
    { "value": "3239", "label": "Oschatz" },
    { "value": "2365", "label": "Osnabrück-Land" },
    { "value": "2366", "label": "Osnabrück-Stadt" },
    { "value": "2336", "label": "Osterholz-Scharmbeck" },
    { "value": "5339", "label": "Paderborn" },
    { "value": "9153", "label": "Passau mit Außenstellen" },
    { "value": "2338", "label": "Peine" },
    { "value": "9154", "label": "Pfaffenhofen a. d. Ilm - Pfaffenhofen" },
    { "value": "2841", "label": "Pforzheim" },
    { "value": "2849", "label": "Pforzheim Außenstelle Neuenbürg" },
    { "value": "2131", "label": "Pinneberg" },
    { "value": "2735", "label": "Pirmasens" },
    { "value": "3210", "label": "Pirna" },
    { "value": "3223", "label": "Plauen" },
    { "value": "2126", "label": "Plön" },
    { "value": "3046", "label": "Potsdam" },
    { "value": "4165", "label": "Pößneck" },
    { "value": "2367", "label": "Quakenbrück" },
    { "value": "3117", "label": "Quedlinburg" },
    { "value": "2839", "label": "Rastatt" },
    { "value": "2127", "label": "Ratzeburg" },
    { "value": "5340", "label": "Recklinghausen" },
    { "value": "9244", "label": "Regensburg" },
    { "value": "5126", "label": "Remscheid" },
    { "value": "2128", "label": "Rendsburg" },
    { "value": "2878", "label": "Reutlingen" },
    { "value": "5347", "label": "Rheda-Wiedenbrück - Wiedenbrück" },
    { "value": "2604", "label": "Rheingau-Taunus Verwaltungsstelle Bad Schwalbach" },
    { "value": "2637", "label": "Rheingau-Taunus Verwaltungsstelle Rüdesheim" },
    { "value": "4081", "label": "Ribnitz-Damgarten" },
    { "value": "9156", "label": "Rosenheim m. ASt Wasserburg" },
    { "value": "4079", "label": "Rostock" },
    { "value": "2340", "label": "Rotenburg (Wümme)" },
    { "value": "2819", "label": "Rottweil" },
    { "value": "2815", "label": "Rottweil Außenstelle Oberndorf" },
    { "value": "1040", "label": "Saarbrücken I" },
    { "value": "1055", "label": "Saarbrücken II" },
    { "value": "1010", "label": "Saarlouis" },
    { "value": "3106", "label": "Salzwedel" },
    { "value": "5222", "label": "Sankt Augustin" },
    { "value": "5211", "label": "Schleiden" },
    { "value": "2882", "label": "Schorndorf" },
    { "value": "9159", "label": "Schrobenhausen m. ASt Neuburg" },
    { "value": "9247", "label": "Schwabach" },
    { "value": "2624", "label": "Schwalm-Eder Verwaltungsstelle Fritzlar" },
    { "value": "2632", "label": "Schwalm-Eder Verwaltungsstelle Melsungen" },
    { "value": "2642", "label": "Schwalm-Eder Verwaltungsstelle Schwalmstadt" },
    { "value": "9248", "label": "Schwandorf mit Außenstelle Neunburg v. W." },
    { "value": "3218", "label": "Schwarzenberg" },
    { "value": "9249", "label": "Schweinfurt" },
    { "value": "5341", "label": "Schwelm" },
    { "value": "4090", "label": "Schwerin" },
    { "value": "2843", "label": "Schwetzingen" },
    { "value": "2883", "label": "Schwäbisch Gmünd" },
    { "value": "2884", "label": "Schwäbisch Hall" },
    { "value": "2857", "label": "Schwäbisch Hall Außenstelle Crailsheim" },
    { "value": "5220", "label": "Siegburg" },
    { "value": "5342", "label": "Siegen" },
    { "value": "2885", "label": "Sigmaringen" },
    { "value": "2881", "label": "Sigmaringen Außenstelle Bad Saulgau" },
    { "value": "2740", "label": "Simmern-Zell" },
    { "value": "2818", "label": "Singen" },
    { "value": "2844", "label": "Sinsheim" },
    { "value": "5343", "label": "Soest" },
    { "value": "5128", "label": "Solingen" },
    { "value": "2341", "label": "Soltau" },
    { "value": "4159", "label": "Sondershausen" },
    { "value": "4170", "label": "Sonneberg" },
    { "value": "2741", "label": "Speyer-Germersheim" },
    { "value": "1060", "label": "St. Wendel" },
    { "value": "2343", "label": "Stade" },
    { "value": "2344", "label": "Stadthagen" },
    { "value": "9161", "label": "Starnberg" },
    { "value": "3107", "label": "Staßfurt" },
    { "value": "5311", "label": "Steinfurt" },
    { "value": "3108", "label": "Stendal" },
    { "value": "3224", "label": "Stollberg" },
    { "value": "4082", "label": "Stralsund" },
    { "value": "9162", "label": "Straubing" },
    { "value": "3064", "label": "Strausberg" },
    { "value": "2893", "label": "Stuttgart I" },
    { "value": "2895", "label": "Stuttgart II" },
    { "value": "2897", "label": "Stuttgart III" },
    { "value": "2892", "label": "Stuttgart IV" },
    { "value": "2896", "label": "Stuttgart Zentrales Konzernprüfungsamt" },
    { "value": "2899", "label": "Stuttgart-Körpersch." },
    { "value": "4171", "label": "Suhl" },
    { "value": "2345", "label": "Sulingen" },
    { "value": "2346", "label": "Syke" },
    { "value": "2880", "label": "Tauberbischofsheim" },
    { "value": "2852", "label": "Tauberbischofsheim Außenstelle Bad Mergentheim" },
    { "value": "9163", "label": "Traunstein" },
    { "value": "2742", "label": "Trier" },
    { "value": "2821", "label": "Tuttlingen" },
    { "value": "2886", "label": "Tübingen" },
    { "value": "2347", "label": "Uelzen-Lüchow" },
    { "value": "9252", "label": "Uffenheim" },
    { "value": "2888", "label": "Ulm" },
    { "value": "2368", "label": "Vechta" },
    { "value": "5139", "label": "Velbert" },
    { "value": "2348", "label": "Verden (Aller)" },
    { "value": "5102", "label": "Viersen" },
    { "value": "2822", "label": "Villingen-Schwenningen" },
    { "value": "2804", "label": "Villingen-Schwenningen Außenstelle Donaueschingen" },
    { "value": "2890", "label": "Waiblingen" },
    { "value": "9254", "label": "Waldsassen" },
    { "value": "2820", "label": "Waldshut-Tiengen" },
    { "value": "2816", "label": "Waldshut-Tiengen Außenstelle Bad Säckingen" },
    { "value": "2891", "label": "Wangen" },
    { "value": "5345", "label": "Warburg" },
    { "value": "4075", "label": "Waren (Müritz) - Waren" },
    { "value": "5346", "label": "Warendorf" },
    { "value": "9255", "label": "Weiden i.d.Opf." },
    { "value": "9168", "label": "Weilheim-Schongau" },
    { "value": "2877", "label": "Weingarten - Ravensburg" },
    { "value": "2847", "label": "Weinheim" },
    { "value": "5130", "label": "Wesel" },
    { "value": "2369", "label": "Westerstede" },
    { "value": "2639", "label": "Wetzlar" },
    { "value": "2640", "label": "Wiesbaden I" },
    { "value": "2643", "label": "Wiesbaden II" },
    { "value": "2370", "label": "Wilhelmshaven" },
    { "value": "2350", "label": "Winsen (Luhe)" },
    { "value": "5221", "label": "Wipperfürth" },
    { "value": "4080", "label": "Wismar" },
    { "value": "5348", "label": "Witten" },
    { "value": "3115", "label": "Wittenberg" },
    { "value": "2743", "label": "Wittlich" },
    { "value": "2351", "label": "Wolfenbüttel" },
    { "value": "9104", "label": "Wolfratshausen - Bad Tölz" },
    { "value": "2744", "label": "Worms-Kirchheimbolanden" },
    { "value": "9258", "label": "Wunsiedel mit Außenstelle Selb" },
    { "value": "5131", "label": "Wuppertal-Barmen" },
    { "value": "5132", "label": "Wuppertal-Elberfeld" },
    { "value": "9257", "label": "Würzburg mit Außenstelle Ochsenfurt" },
    { "value": "9259", "label": "Zeil am Main mit Außenstelle Ebern" },
    { "value": "2352", "label": "Zeven" },
    { "value": "3228", "label": "Zschopau" },
    { "value": "3227", "label": "Zwickau" },
    { "value": "9170", "label": "Zwiesel m. ASt Viechtach" },
    { "value": "2876", "label": "Öhringen" },
    { "value": "2887", "label": "Überlingen (Bodensee)" },
]

def get_all_tax_offices():
    """
    Returns a list of all tax offices.

    Returns:
        List of dictionaries with tax office information
    """
    return TAX_OFFICE_OPTIONS

def get_tax_office_by_code(code):
    """
    Get tax office information by code.

    Args:
        code: Tax office code (string)

    Returns:
        Dictionary with tax office information or None if not found
    """
    all_offices = TAX_OFFICE_OPTIONS
    for office in all_offices:
        if office["value"] == code:
            return office
    return None
