name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docker-image:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: set up qemu
          uses: docker/setup-qemu-action@v2

        - name: set up buildx
          uses: docker/setup-buildx-action@v2

        - name: generate image identifier
          id: image
          uses: ASzc/change-string-case-action@v5
          with:
            string: ${{ github.repository_owner }}

        - name: login to ghcr
          uses: docker/login-action@v2
          if: ${{ github.ref == 'refs/heads/main'}}
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: build web image (production)
          uses: docker/build-push-action@v3
          if: ${{ github.ref == 'refs/heads/main'}}
          with:
            context: .
            push: ${{ github.ref == 'refs/heads/main' }}
            tags: |
              ghcr.io/${{ steps.image.outputs.lowercase }}/norman-mcp-server:latest
              ghcr.io/${{ steps.image.outputs.lowercase }}/norman-mcp-server:${{ github.sha }}

            build-args: |
              RELEASE=${{ github.sha }}
            cache-from: type=gha
            cache-to: type=gha,mode=max

  deploy-production:
    needs: build-docker-image
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'norman-finance'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: draft sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          finalize: false

      - name: read image identifiers
        id: image
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository_owner }}

      - name: update ai image
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: docker service update norman_mcp --image ghcr.io/${{ steps.image.outputs.lowercase }}/norman-mcp-server:${{ github.sha }} --with-registry-auth

      - name: finalize sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          finalize: true